### ISSUE TITLE
Is it possible to extract comments/replies?

### ISSUE THREAD

**Issue by k-dutra** [chrisumphlett/zdeskR#5]
Hi, 

I'd like to extract the replies that the company had gave for each ticket, is it possible with zdeskR?

**Comment by chrisumphlett** [comment]
No. Zendesk does have an API endpoint for this I believe but I have not had a reason to use it, and it would be both a) a lot of (semi-unstructured) data to handle and b) likely contain sensitive and personal information we didn’t want to collect proactively.

you’re welcome to contribute to the package, I would help with you trying to add it. 

https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/#list-comments
this requires an api call for every ticket too. It’s a much more computationally expensive process to create.

**Comment by k-dutra** [comment]
Hi Chris, thank you for the answer. Usually, I just use packages, but if you can help me, maybe I can contribute to the ZdeskR package. I've understood your arguments, and I agree with almost everything. In my case, I need the ticket's replies to support legal arguments in court. Thus, it is true that I don't need to collect all comments/replies proactively, just for some tickets. Then, I used your development in ZdeskR to do this. Look:

```r

#function to extract tickets comments/replies
get_tickets_comments <- function(email_id, token, subdomain, ticket_id,
                        remove_cols = NULL) {
  user <- paste0(email_id, "/token")
  pwd <- token
  ticket_id <- ticket_id
 
url <- paste0(
      "https://", subdomain,
      ".zendesk.com/api/v2/tickets/", ticket_id, "/comments?")

request_ticket <- httr::RETRY("GET",
                                       url = url,
                                       httr::authenticate(user, pwd))
   
  }

#Data frame with tickets ids. For example, I've used the function get_tickets from ZdeskR to get all tickets that I needed based in a start date, and in this data.frame I got the tickets id.
list_tickets_tocomments <- all_tickets %>% 
  filter(status != "deleted") %>% 
  select(id)
  
#loop to store results of comments/replies from multiple tickets
#1º create an empty data frame to store the results
results <- data.frame()


#2º loop in fact
for (id in list_tickets_tocomments$id) {
  comments_extracted <- get_tickets_comments(email_id = "email_id", token = "token",
                           subdomain = "subdomain", ticket_id = id, remove_cols = NULL)
  
response_text <- httr::content(comments_extracted, as = "text")
parsed_response <- jsonlite::fromJSON(response_text)

comments_extracted2 <- as.data.frame(parsed_response$comments) %>% 
  select(author_id, body, created_at) %>% #here, I've selected only the relevant variables to my analysis
  mutate(ticket_id = id) # to identify each comment with the ticket id.
  
#store results in a data.frame with rows binded
  results <- rbind(results, comments_extracted2)
}

```

**Comment by chrisumphlett** [comment]
did that run successfully for you? I'm getting a 404 error when I try to run the first part, just running the pieces of the function one by one.

**Comment by k-dutra** [comment]
Hi Chris, you are right. I've tried, and I got the same error. It worked the first time for me because I had used it with a particular list of tickets. After your comment, I tried with a general list, and the 404 error appeared. I discovered that it occurs because of tickets with a status equal to "deleted". Thus, I've changed the script, and everything runs well. Could you please try again? The previous comment was updated.  

The changes were in:

- #Data frame with tickets ids. For example, I've used the function get_tickets from ZdeskR to get all tickets that I needed based in a start date, and in this data.frame I got the tickets id.

list_tickets_tocomments <- all_tickets %>% 
  **filter(status != "deleted") %>% 
  select(id)**
  

and in:

- #2º loop in fact

for (id in list_tickets_tocomments **$id** ) {.....

**Comment by chrisumphlett** [comment]
I think I had tried to pull a recent ticket, but did that lazily-- the ticket id I was trying was quite old so that may have been the problem. Without changing anything on what I did before, and using a more recent ticket id, the api call is returning successfully. 

The conversion from a list to a data frame is something I want to do inside of the function-- generally speaking that is something that is desired. That would mean moving everything _through comments_extracted2_ inside of `get_tickets_comments()`, but excluding the steps built for working with multiple tickets (creating the empty data frame, looping across a list of tickets).

I was wrong in my initial analysis of the complexity. This function should just work for a single ticket-- looking up multiple tickets and binding those together can be handled outside (as you did here).  Thus this isn't "much more computationally expensive"-- you might need to run the function many times, but you're not hitting the API many times within one function call.

Can you update the code to that?

Are you interested in trying to contribute directly to the package? If so, you could make a pull request and add a new .R file with the function and its ROxygen2 documentation. If not, that's fine by building and testing this you've helped me and I can do the work on the package.

If you do that you get to show up in GH like this (look for my name here: https://github.com/mitchelloharawild/vitae/graphs/contributors). Either way I'll give you credit in the NEWS for this release.

**Comment by chrisumphlett** [comment]
Also -- coincidentally I had someone at my company ask if we could pull conversations for something else so I now have a little more incentive to get this moving too :) Good timing.

**Comment by k-dutra** [comment]
Hi Chris, I'm glad to hear everything. Thus, I will try to contribute directly to the package. I got the explanation about what to change in  `get_tickets_comments()`. I have just one doubt, at the moment, about the data frame because, in the example, I've used only three variables, and every ticket can have different variables, thereby the rbind might not work. Do you believe that in the function we can put a list of variables to be extracted in the comments/replies, and the user can choose what variables they want to extract? Could one parameter of the function be a list? for example, c("author_id", "body", "created_at"). Or do you have other recommendations?

Thank you in advance for the possibility and your help.

**Comment by chrisumphlett** [comment]
This is an issue with `get_tickets()` as well. Line 106 in that function handles it-- when you bind rows together they don't have to have the same columns, new columns get created and missing columns get null values.

I do think it brings up a good point, whether or not to return columns like `html_body`/`plain_body`/`body` and all of the `via` and `metadata` fields.  Below are my thoughts, I'm interested in yours. You've seen a lot more data than me. I'm only looking at a single ticket. Regardless, I think it's better to pick some columns to remove or make optional, and then include everything else that comes out (anything that is only sometimes included).

* `via` : I feel strongly NO here, because most if not all of these are pulled down with `get_tickets()`
* `metadata` : I can see more value here, also more risk because it pulls in additional potential personal information: location, lat/long, ip address. I lean towards making this optional (by default, do not return but someone could flip it to TRUE and get these columns)
* `body`: only return one of them, and `body` is the cleanest one
* drop `audit_id`, `public`
* do not try to keep the nested data frame for the attachment, but include some indication of whether or not there was an attachment (I only saw one, the name was 'redacted.txt')

The `*id` columns that are getting put in scientific notation should be returned as strings and render the full string.

**Comment by chrisumphlett** [comment]
@k-dutra what do you think about the above?

**Comment by k-dutra** [comment]
Hi Chris, I'm so sorry. I have a project to finish today, this week has been too busy. This weekend I will answer you and work in the new function.

**Comment by k-dutra** [comment]
Finished! 🥳 

Hi Chris, how are you doing? I hope that this message finds you well. 
Finally I had time and was able to finish the function. Can you review it and see if it is optimised enough? I will do the "pull request" soon.


```
#function to extract tickets comments/replies
get_tickets_comments <- function(email_id, token, subdomain, ticket_id,
                                 add_cols= NULL, sensitive_data=F) {
  user <- paste0(email_id, "/token")
  pwd <- token
  ticket_id <- ticket_id
  
  url <- paste0(
    "https://", subdomain,
    ".zendesk.com/api/v2/tickets/", ticket_id, "/comments?")
  
  request_ticket <- httr::RETRY("GET",
                                url = url,
                                httr::authenticate(user, pwd))

  response_text <- httr::content(request_ticket, as = "text")
  parsed_response <- jsonlite::fromJSON(response_text)

  columns <- c("id", "type", "author_id", "body", "created_at", "have_attachments") #default columns
  
  if(length(add_cols)!= 0) {
    columns_final <- c(columns, add_cols)
    }
  
  sensitive_data_columns <- c("metadata") 
  if(sensitive_data== T) { #default without sensitive data
    columns_final <- c(columns_final, sensitive_data_columns)
  }
  
 
  comments_extracted2 <- as.data.frame(parsed_response$comments) %>% 
  mutate(have_attachments = ifelse(sapply(attachments, function(list_element) length(list_element)==0), "No", "Yes")) %>%
  select(all_of(columns_final))
}
```

Regarding your previous answer about columns we should keep or drop, I strongly agree with everything, and I don't have additional comments.

**Comment by chrisumphlett** [comment]
Thanks. Will move the discussion to your PR
